version: "3.5"
services:
  dns-lab:
    image: leapdns
    environment:
      - DNS_FORWARDER=8.8.8.8
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "953:953/tcp"
      - "953:953/udp"
    volumes:
      - /opt/dns-data:/data
      - /opt/dns-config:/dns-config
