---
apiVersion: v1
kind: Service
metadata:
  name: dns
  namespace: dns
  labels:
    app: dns
spec:
  type: LoadBalancer
  ports:
    - name: dns-queries
      port: 53
      targetPort: 53
    - name: dns-zone-transfer
      port: 8086
      targetPort: 8086
  selector:
    app: dns
