
version: "1.0"
services:
  dns-master:
          image: sapnamed:latest
    environment:
      - DNS_FORWARDER=8.8.8.8
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "953:953/tcp"
    volumes:
      - /opt/named/data:/data
      - /opt/named/config:/dns-config
      - /opt/named/etc:/etc
    deploy:
        replicas: 1
